# Setup
title:               I Like
tagline:             Crypto, Forensics, etc.
description:         I will post write-up of CTF and some interesting researches. Made by <a href="https://www.github.com/L0Z1K" target="_blank">L0Z1K</a>.
url:                 https://L0Z1K.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:              L0Z1K
name:              Baek Seungyun
url:               https://L0Z1K.github.io
email:             qortmddbs731@korea.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
